// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "post": {
                "description": "Check if user with a certain role has access to an url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Check if user with a certain role has access to an url",
                "operationId": "access-handler",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pdp.AccessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pdp.AccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pdp.AccessRequest": {
            "description": "Requests access to a url for a user with a certain role given by token",
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pdp.AccessResponse": {
            "type": "object",
            "properties": {
                "permission": {
                    "$ref": "#/definitions/pdp.Permission"
                }
            }
        },
        "pdp.Permission": {
            "type": "string",
            "enum": [
                "allow",
                "deny"
            ],
            "x-enum-varnames": [
                "Allow",
                "Deny"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0-alpha",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Heimdall API",
	Description:      "This is the Heimdall API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
